package com.miaoshaproject.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user info.id
     *
     * @mbggenerated Sat Jul 27 12:46:08 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user info.id
     *
     * @return the value of user info.id
     *
     * @mbggenerated Sat Jul 27 12:46:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user info.id
     *
     * @param id the value for user info.id
     *
     * @mbggenerated Sat Jul 27 12:46:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}